app = "face-recognition-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  API_HOST = "0.0.0.0"
  API_DEBUG = "False"
  LOG_LEVEL = "INFO"
  FACE_RECOGNITION_MODEL = "hog"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "face_recognition_data"
  destination = "/app/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024



